FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3 python3-pip openssh-client sshpass vim nano
RUN pip install ansible

RUN useradd -m ansible
USER ansible
WORKDIR /home/ansible

CMD ["/bin/bash"]
