# Generated by Django 4.2.24 on 2025-09-11 02:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0005_transaction_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'ordering': ['ticker'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
        migrations.AlterModelOptions(
            name='userstock',
            options={'verbose_name': 'User Stock Position', 'verbose_name_plural': 'User Stock Positions'},
        ),
        migrations.AddField(
            model_name='stocks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='industry',
            field=models.CharField(blank=True, default='', help_text='Stock industry', max_length=100),
        ),
        migrations.AddField(
            model_name='stocks',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is stock actively traded'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='market_cap',
            field=models.BigIntegerField(blank=True, help_text='Market capitalization', null=True),
        ),
        migrations.AddField(
            model_name='stocks',
            name='sector',
            field=models.CharField(blank=True, default='', help_text='Stock sector', max_length=100),
        ),
        migrations.AddField(
            model_name='stocks',
            name='volume',
            field=models.BigIntegerField(default=0, help_text='Trading volume'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='curr_price',
            field=models.DecimalField(decimal_places=2, help_text='Current stock price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='ticker',
            field=models.CharField(db_index=True, help_text='Stock ticker symbol', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per share', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stock_symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pancard_image',
            field=models.ImageField(blank=True, null=True, upload_to='pancard_images/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pancard_number',
            field=models.CharField(help_text='PAN Card Number', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(help_text='Phone number with country code', max_length=15),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Average purchase price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='purchase_quantity',
            field=models.PositiveIntegerField(help_text='Number of shares owned', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='userstock',
            unique_together={('user', 'stock')},
        ),
    ]
